name=ArduLoFi
version=1.0.0
author=NamNamIoT
maintainer=NamNamIoT <thanhnamlt5@gmail.com>
sentence=A lightweight RUI3-based library for ArduLoFi (RAK3172 + ESP32-C3) IoT board.
paragraph=ArduLoFi simplifies IoT development for the ArduLoFi board, combining RAK3172 (RUI3) and ESP32-C3 co-processor. It provides easy-to-use examples for P2P/LoRaWAN, hardware peripherals like Modbus, I2C, and a WiFi/MQTT bridge.
category=Communication
url=https://github.com/NamNamIoT/ArduLoFi
architectures=*
includes=ArduLoFi.h
depends=ArduLora
